# Generated by Django 5.2.17 on 2026-10-02 08:40

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import reports.models
import reports.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(blank=True, editable=False, max_length=20, unique=True, verbose_name='référence')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='signalement anonyme')),
                ('accident_type', models.CharField(choices=[('COLLISION_VEHICLES', 'Collision entre véhicules'), ('COLLISION_PEDESTRIAN', 'Collision avec piéton'), ('MOTORCYCLE', 'Accident de moto'), ('SINGLE_VEHICLE', 'Accident de véhicule seul'), ('ROLLOVER', 'Renversement'), ('OTHER', 'Autre')], max_length=30, verbose_name="type d'accident")),
                ('accident_date', models.DateField(verbose_name="date de l'accident")),
                ('accident_time', models.TimeField(verbose_name="heure de l'accident")),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyenne'), ('SEVERE', 'Grave'), ('CRITICAL', 'Très grave')], default='MEDIUM', max_length=10, verbose_name='gravité estimée')),
                ('vehicle_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='nombre de véhicules')),
                ('injured_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='nombre de blessés')),
                ('death_count', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(500)], verbose_name='nombre de décès')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='description')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=reports.models.report_photo_path, validators=[reports.validators.validate_photo_extension, reports.validators.validate_photo_size, reports.validators.validate_photo_content], verbose_name='photographie')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='localisation')),
                ('latitude', models.FloatField(blank=True, editable=False, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, editable=False, null=True, verbose_name='longitude')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('VERIFIED', 'Vérifié'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10, verbose_name='statut')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='date de traitement')),
                ('admin_note', models.TextField(blank=True, verbose_name="note de l'administrateur")),
                ('is_demo', models.BooleanField(default=False, help_text='Créé par la commande seed_demo : ne correspond pas à un accident réel.', verbose_name='donnée de démonstration')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date du signalement')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='déclarant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reports', to=settings.AUTH_USER_MODEL, verbose_name='traité par')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-accident_date'], name='report_status_date_idx'), models.Index(fields=['accident_date'], name='report_date_idx'), models.Index(fields=['accident_type'], name='report_type_idx'), models.Index(fields=['severity'], name='report_severity_idx'), models.Index(fields=['is_anonymous'], name='report_anonymous_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_anonymous', False), ('user__isnull', True), _connector='OR'), name='report_anonymous_has_no_user'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__gte', -90), ('latitude__lte', 90), ('longitude__gte', -180), ('longitude__lte', 180)), ('latitude__isnull', True), _connector='OR'), name='report_valid_coordinates')],
            },
        ),
    ]
