# Generated by Django 5.2.17 on 2026-10-07 19:12

import django.db.models.deletion
import reports.models
import reports.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_vehicle_count_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to=reports.models.report_photo_path, validators=[reports.validators.validate_photo_extension, reports.validators.validate_photo_size, reports.validators.validate_photo_content], verbose_name='photographie')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ajoutée le')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_photos', to='reports.accidentreport', verbose_name='signalement')),
            ],
            options={
                'verbose_name': 'photo de signalement',
                'verbose_name_plural': 'photos de signalement',
                'ordering': ['created_at'],
            },
        ),
    ]
