# Generated by Django 5.2
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_reportphoto"),
    ]

    operations = [
        migrations.AddField(
            model_name="accidentreport",
            name="accident_cause",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EXCESSIVE_SPEED", "Vitesse excessive"),
                    ("RULE_VIOLATION", "Non-respect des règles"),
                    ("IMPAIRED_DRIVING", "Conduite sous l'emprise des stupéfiants et de l'alcool"),
                    ("REDUCED_VISIBILITY", "Visibilité dégradée"),
                    ("MECHANICAL_FAILURE", "Défaillance mécanique"),
                    (
                        "WEATHER_AND_ROAD_CONDITIONS",
                        "Mauvaises conditions météorologiques et état de la chaussée",
                    ),
                ],
                max_length=30,
                null=True,
                verbose_name="Causes de l'accident",
            ),
        ),
    ]
